CREATE TABLE NATURA_POSTS(
ID_POST NUMBER PRIMARY KEY,
CONTEUDO_POST VARCHAR2(3000),
DATA_POST DATE
);

select*from natura_posts;

CREATE TABLE NATURA_TOPICOS(
ID_TOPICO NUMBER PRIMARY KEY,
TITULO VARCHAR2(100),
CATEGORIA VARCHAR2(100)
);

select*from natura_topicos;

CREATE TABLE NATURA_USUARIOS(
CPF VARCHAR2(11) UNIQUE,
USERNAME VARCHAR2(30) PRIMARY KEY,
EMAIL VARCHAR2(255) UNIQUE,
NIVEL_NATURA VARCHAR2(15)
);


select*from natura_usuario;

COMMIT;
